spring:
  datasource:
    driverclassname: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/winter?serverTimezone=UTC
    username: hundun
    password: 123456
  security:
    user:
      name: user
      password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml